dist: trusty
language: node_js
node_js:
- stable
script:
- npm run coverage
after_success:
- npm run publish-coverage
branches:
    only: development
notifications:
    email:
        recipients:
        - 1804094745@qq.com      # change to your own address
        - 1666298161@qq.com    # uae other (optional)
        on_success: never        # default: change
        on_failure: always       # default: always
